### ISSUE TITLE
Prevent creating self reference link

### ISSUE THREAD

**Issue by EdiWang** [EdiWang/Elf#10]
When creating links that match both domain and URL action of the current website, return the link itself.

e.g.:

Given existing or non-existing link https://go.edi.wang/fw/abcd1234
When user try to create a link with origin link https://go.edi.wang/fw/abcd1234
Return https://go.edi.wang/fw/abcd1234 and do not create a new link

**Comment by os1r1s110** [comment]
@EdiWang quick question related to this. Has this been added to prevent someone creating an infinite redirection loop?

I'm asking because I'm trying to use Elf to create a redirection link within an app which is redirecting to another endpoint of the same app (I embedded the url forwarder within the app) but it generates an error due to the host/authority and the scheme being the same for both the origin url (final target) and the forwarding link origin. 

I'm wondering if it wouldn't be better to simply ensure the link is not pointing to another redirection endpoint instead of simply blocking all requests to the same domain. (I can certainly modify it and use a local clone of the code, but I am legitimately interested in knowing what you think about it). 

I think I get it though, this is supposed to be used solely as a redirection service, hence why it prevents all requests to its own domain... which makes sense. But I think it could be modified in a way that would let it be implemented for "in-app" redirection too, what do you think?

**Comment by EdiWang** [comment]
@os1r1s110 

The idea behind the design of Elf is explained in my blog post: https://edi.wang/post/2019/6/19/building-a-net-core-url-forward-service this post explains why link to same domain will be blocked. 

However, what you are suggesting also make sense. I am reopening this issue to add an appsettings key to allow these in-app redirection, so that you won't need to modify the source code. But still, please keep in mind this is not safe for the system as explained in the blog post.

**Comment by os1r1s110** [comment]
I just read your blog post, I see that you effectively implemented it to prevent infinite loops. Though I think you could simply extend the check to ensure the link does not point back to the forwarding url? 

Such as a link https://go.edi.wang/fw/a that would point to https://go.edi.wang/fw/b would be invalid, but the same link pointing to https://go.edi.wang/other/.... would pass validation, this would effectively prevent infinite looping, except if the link points to another url forwarding endpoint in the same app, but then can you really prevent it?

**Comment by EdiWang** [comment]
@os1r1s110 thanks for your suggestion. I implemented the forward endpoint check in #54
